---
- hosts: odva-test
  become: yes
  roles:
  - role: java
  - { role: odva, odva_user: odva_test, odva_port: 8081, odva_interval: 60 }
    #  - role: docker-io
    #  - role: prometheus-container
    #  - role: prometheus-odva
    #  - role: grafana-dockerized
    #  - role: grafana-container
    #  - role: nginx
    #  - role: nginx-odva
